---
driver:
  name: vagrant
  boot_timeout: 1200

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      cpus: 4
      memory: 1024

suites:
  - name: default
    run_list:
      - recipe[docker-prom::base]
      - recipe[docker-prom::docker]
      - recipe[docker-prom::prometheus]
      - recipe[docker-prom::cadvisor]      
      - recipe[docker-prom::nodeexporter]
      - recipe[docker-prom::grafana]      
    verifier:
      inspec_tests:
        - test/integration/docker
        - test/integration/prometheus
        - test/integration/cadvisor        
        - test/integration/nodeexporter
        - test/integration/grafana
